[[IgnoredVulns]]
id = "RUSTSEC-2024-0384"
reason = "Low risk (instant is unmaintained)"

[[IgnoredVulns]]
id = "RUSTSEC-2024-0436"
reason = "Low risk (paste is unmaintained)"

[[IgnoredVulns]]
id = "RUSTSEC-2024-0370"
reason = "Low risk (proc-macro-error is unmaintained)"

[[IgnoredVulns]]
id = "RUSTSEC-2025-0056"
reason = "Low risk (adler crate is unmaintained, use adler2 instead)"

[[IgnoredVulns]]
id = "RUSTSEC-2023-0071"
reason = "No solution yet"
# https://osv.dev/vulnerability/RUSTSEC-2023-0071
# Patches
#  No patch is yet available, however work is underway to migrate to a fully constant-time implementation.
# Workarounds
#  The only currently available workaround is to avoid using the rsa crate in settings where attackers are 
#  able to observe timing information, e.g. local use on a non-compromised computer is fine.

[[IgnoredVulns]]
id = "RUSTSEC-2025-0134"
reason = "Low risk (rustls-pemfile is unmaintained)"
